# Generated by Django 5.1.5 on 2026-03-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='total_usage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
